import { Signal, Strategy } from "./types";

export const strategies: Strategy[] = [
  {
    id: "smc",
    label: "Smart Money Concepts",
    short: "SMC",
    description: "Liquidity sweeps, order blocks, and structure shifts.",
  },
  {
    id: "ict",
    label: "ICT Concepts",
    short: "ICT",
    description: "BOS / CHoCH, fair value gaps, and order block confluence.",
  },
  {
    id: "wyckoff",
    label: "Wyckoff Phase",
    short: "Wyckoff",
    description: "Accumulation / distribution phase and AR detection.",
  },
  {
    id: "snr",
    label: "Supply & Resistance",
    short: "SNR",
    description: "Body-only levels with freshness and volume/attempt validation.",
  },
  {
    id: "r-multiple",
    label: "R-Multiple Quality",
    short: "R-Mult",
    description: "Ranks setups by risk-reward quality, not just confluence.",
  },
  {
    id: "propfirm",
    label: "Prop Firm Mode",
    short: "PropFirm",
    description: "Filters setups by max drawdown / daily loss compliance.",
  },
];

export const mockSignals: Signal[] = [
  {
    id: "sig-1",
    instrument: "XAUUSD",
    assetClass: "metals",
    direction: "long",
    confluence: 91,
    session: "london",
    timeframe: "H1",
    strategies: ["smc", "wyckoff", "propfirm"],
    riskReward: 3.1,
    entry: 2412.4,
    stop: 2406.8,
    target: 2429.2,
    detectedAt: "2m ago",
  },
  {
    id: "sig-2",
    instrument: "EURUSD",
    assetClass: "forex",
    direction: "long",
    confluence: 86,
    session: "new-york",
    timeframe: "M15",
    strategies: ["ict", "r-multiple"],
    riskReward: 2.4,
    entry: 1.0842,
    stop: 1.0821,
    target: 1.0893,
    detectedAt: "6m ago",
  },
  {
    id: "sig-3",
    instrument: "NAS100",
    assetClass: "indices",
    direction: "short",
    confluence: 78,
    session: "new-york",
    timeframe: "H1",
    strategies: ["smc", "snr"],
    riskReward: 1.9,
    entry: 19842,
    stop: 19910,
    target: 19710,
    detectedAt: "11m ago",
  },
  {
    id: "sig-4",
    instrument: "GBPUSD",
    assetClass: "forex",
    direction: "short",
    confluence: 72,
    session: "london",
    timeframe: "M30",
    strategies: ["ict", "wyckoff"],
    riskReward: 2.0,
    entry: 1.2731,
    stop: 1.2758,
    target: 1.2677,
    detectedAt: "14m ago",
  },
  {
    id: "sig-5",
    instrument: "XAUUSD",
    assetClass: "metals",
    direction: "short",
    confluence: 64,
    session: "asian",
    timeframe: "M15",
    strategies: ["snr"],
    riskReward: 1.6,
    entry: 2419.1,
    stop: 2423.7,
    target: 2410.3,
    detectedAt: "19m ago",
  },
  {
    id: "sig-6",
    instrument: "USTEC",
    assetClass: "indices",
    direction: "long",
    confluence: 83,
    session: "new-york",
    timeframe: "H4",
    strategies: ["smc", "r-multiple", "propfirm"],
    riskReward: 2.8,
    entry: 19601,
    stop: 19520,
    target: 19828,
    detectedAt: "24m ago",
  },
];

export const sessionMeta: Record<
  Signal["session"],
  { label: string; hours: string }
> = {
  asian: { label: "Asian", hours: "00:00–08:00 UTC" },
  london: { label: "London", hours: "08:00–16:00 UTC" },
  "new-york": { label: "New York", hours: "13:00–21:00 UTC" },
};
